Resolved compilation issue due to wrong path and variable name in the import statement ERROR in src/environments/environment.dev-custom.ts(1,31): error TS2307: Cannot find module '../config/custom/custom' src/environments/environment.prod-custom.ts(1,31): error TS2307: Cannot find module '../config/custom/custom'.